name: jaspr_bloc
description: A Jaspr implementation of the bloc state management library.
version: 1.0.1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  bloc: ^9.2.0
  jaspr: ^0.22.1
  meta: ^1.11.0

dev_dependencies:
  bloc_lint: ^0.3.6
  jaspr_lints: ^0.6.0
  jaspr_test: ^0.22.1
  lints: ^6.0.0
  test: ^1.24.0
